### PR TITLE
Test matrix for Elixir/OTP versions

### PR DESCRIPTION
**Pull request by ciaranmcnulty**
Adds the explicit versions that messages and gherkin were using in their release scripts - expected to fail but we can then bump to working versions

### CODE REVIEW

**Comment by mattwynne** [comment]
@ciaranmcnulty I merged this and now the tests are failing. Is that what you expected? What's the next step?

**Comment by ciaranmcnulty** [comment]
I've totally lost context on this after 9mo 😅 

IIRC the releases were using a different version and failing, and this was synchronising the version so that the tests failed _too_

I'm not sure it should have been merged, as I don't know how releases are working now. The short version is the test should use the same version(s) as the other workflows.

**Comment by mpkorstanje** [comment]
@mattwynne this is some fallout from @ciaranmcnulty attempt to use docker to build messages/gherkin. The problem with the docker approach was that the release action had stopped working due to a silent upgrade of Githubs Ubuntu Docker image. We did not notice this in test because the tests using docker used a different version of the Elixir tooling.

Unfortunately, the versions of the tooling we use to build Elixir (Githubs Ubuntu image) cannot longer build Elixir.

I would suggest reverting this MR, and looking at what it takes to build Elixir with the current Ubuntu image provided by GitHub. For the time being Erlang has been disabled in messages and gherkin.

**Comment by mattwynne** [comment]
Woah OK, that's a shame. @WannesFransen1994 any advice here on the underlying problem?

In the meantime I'll revert the MR as you suggest.

**Pull request merged**
